# Generated by Django 3.0 on 2020-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_allproduct_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='allproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='allproduct',
            name='unit',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
